apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: backend-tests-go-cuqupgnw
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/chetna14manku_org/backend-tests-go-cuqupgnw:e7e47fad4bd8e5383bd4a408a2811a137724caa6
        name: container-image  
